### ISSUE TITLE
Documentacion

### ISSUE THREAD

**Issue by bbaruque** [NelsonParamo/GI16.M_ProyectoCoyuntura#14]
- [x] Pasar a limpio elección del framework. (Aspectos Relevantes)
- [x] Pasar a limpio Requisitos y Objetivos
- [x] Incluir en Github el producto Backlog
- [x] Subir a Github el codigo inicial

**Comment by NelsonParamo** [comment]
Respecto a la redacción de los requisitos funcionales, ¿debería introducirlos en la memoria?
Mirando el proyecto que me pasaste, están el anexo, por lo que he creado una carpeta con ese nombre y los he metido allí.
