### ISSUE TITLE
Ajustar roles a la aplicación

### ISSUE THREAD

**Issue by NelsonParamo** [NelsonParamo/GI16.M_ProyectoCoyuntura#19]

**Comment by NelsonParamo** [comment]
@bbaruque @santiagoporras 
-------------------------------------------------------------------------------------------------------------------
Estoy teniendo bastantes problemas con los roles de los usuarios de la aplicación, no consigo poner el middleware bien para denegar el acceso a depende que rutas, dependiendo del rol del usuario que tengas.
Lo máximo que he conseguido sería:
- Tener un Super Administrador que tenga acceso a TODO
- Tener un CIERTO NÚMERO de perfiles de Administrador/Editor con acceso a todo MENOS al control de usuarios.
- Los usuarios normales serían invitados, por lo que no se podrían registrar ya que sino adaptarían el rol superior, por lo que después de crear los perfiles de administrador/editor la posibilidad de crear nuevos usuarios se restringiría.

¿Qué os parece esto?¿Valdría?

**Comment by NelsonParamo** [comment]
@bbaruque @santiagoporras 
----------------------------------------------------------------------------------------------------------------------
He hecho ya lo que dijimos de las solicitudes para formar parte de los administradores y queda así

![solicutud](https://user-images.githubusercontent.com/25463172/27428202-a5904b5c-5741-11e7-9e9b-616f9665b6de.JPG)

**Comment by bbaruque** [comment]
Por mi parte, perfecto. Esa pantalla solo la puede ver al administrador ¿verdad? El resto de usuarios no tendrá acceso.

**Comment by bbaruque** [comment]
Como detalle muy menor, los logos arriba en lugar de alinearlos a la izquierda, los pondría en el medio. Es que se pegan mucho al menú y pueden estorbar un poco.

**Comment by NelsonParamo** [comment]
Exacto, solo la puede ver el super administrador, que es el que tiene acceso a la gestión de usuarios.
Ahora mismo cambio los logos.
