### ISSUE TITLE
Crear archivos para memoria

### ISSUE THREAD

**Issue by bbaruque** [NelsonParamo/GI16.M_ProyectoCoyuntura#2]
- [x] Descargar ficheros de UBUVirtual
- [x] Crear carpeta de documentacion
- [x] Completar Objetivos
- [x] subir al repositorio

**Comment by NelsonParamo** [comment]
Ya tengo todos los ficheros creados, y voy a proceder a subirlos al repositorio, tengo unas pequeñas dudas que ya me solucionarás el siguiente día que quedemos.

**Comment by bbaruque** [comment]
El caso es que no veo estos ficheros en el repositorio. Solo veo varios "Ficheros de Prueba". 
Ya que estamos, en vez de ficheros de prueba vacíos, lo que sí suelen tener todos los repositorios en la raíz es un fichero "ReadMe" que incluye la descripción del proyecto nada más entrar en la página.
