### ISSUE TITLE
Trabajo con las tablas.

### ISSUE THREAD

**Issue by NelsonParamo** [NelsonParamo/GI16.M_ProyectoCoyuntura#23]
- [x] Creación del formulario para filtro de búsqueda.
- [x] Mostrar tablas.
- [x] Edición de tablas.

**Comment by NelsonParamo** [comment]
![whatsapp image 2017-05-06 at 12 42 22](https://cloud.githubusercontent.com/assets/25463172/25771728/bbc839c8-3259-11e7-96dc-83070409348e.jpeg)

**Comment by NelsonParamo** [comment]
Revisando la base de datos me he dado cuenta de que no se podían introducir los valores de las distintas subcategorías, por lo que he decidido introducir una relación ternaria entre la variable, el ámbito y las categorías. Las categorías se agruparán luego en una superior.

**Comment by NelsonParamo** [comment]
@santiagoporras @bbaruque 
---------------------------------------------------------------------------------------------------------------------
A la hora de mostrar los datos, quedamos en que los introducía mes a mes y luego si quería mostrarles por trimestres o por años, hacia la media.
Por lo que mi duda es la siguiente:
Si en 2011, Enero = '1.1 ' , Febrero = ' 1,2 ', Marzo = ' Sin datos'
Y yo quiero mostrar la tabla por trimestres...¿Qué hago?¿La media de los que tienen datos?¿Error?

**Comment by santiagoporras** [comment]
Pon la media de los meses en los que tengas datos y pones un asterisco y una nota a pie de tabla que diga, los datos corresponden a los meses de Enero hasta el ultimo mes que tengas datos.
