### ISSUE TITLE
Página del Equipo Coyuntura

### ISSUE THREAD

**Issue by NelsonParamo** [NelsonParamo/GI16.M_ProyectoCoyuntura#40]

**Comment by NelsonParamo** [comment]
@santiagoporras @bbaruque 
---------------------------------------------------------------------------------------------------------------------
Esta es la página del equipo de coyuntura, si me das los correos electrónicos les pongo al lado del nombre.
![eq](https://user-images.githubusercontent.com/25463172/27428154-7a8d2088-5741-11e7-8ef0-70252e0246a0.JPG)

**Comment by santiagoporras** [comment]
Yo pondría mejor el enlace a la página de la ubu en la que están así te quitas de líos de correos y si hay que actualizarlo pues es menos jaleo o puedes tener las dos .

Los correos los puedes sacar de la página de la uni

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________
